#include "PluginProcessor.h"
#include "PluginEditor.h"
AngelVocalAIProcessor::AngelVocalAIProcessor():AudioProcessor(BusesProperties().withInput("Input",juce::AudioChannelSet::stereo(),true).withOutput("Output",juce::AudioChannelSet::stereo(),true)){}
bool AngelVocalAIProcessor::isBusesLayoutSupported(const BusesLayout& l)const{auto i=l.getMainInputChannelSet(),o=l.getMainOutputChannelSet();return i==o&&(i==juce::AudioChannelSet::mono()||i==juce::AudioChannelSet::stereo());}
void AngelVocalAIProcessor::prepareToPlay(double s,int n){sr=s;juce::dsp::ProcessSpec sp{s,(juce::uint32)n,2};hp.prepare(sp);presence.prepare(sp);air.prepare(sp);deesser.prepare(sp);comp.prepare(sp);makeup.prepare(sp);applySettings();}
void AngelVocalAIProcessor::applySettings(){hp.coefficients=juce::dsp::IIR::Coefficients<float>::makeHighPass(sr,hpHz,.7071f);presence.coefficients=juce::dsp::IIR::Coefficients<float>::makePeakFilter(sr,3200,.8f,juce::Decibels::decibelsToGain(presDb));air.coefficients=juce::dsp::IIR::Coefficients<float>::makeHighShelf(sr,9000,.7f,juce::Decibels::decibelsToGain(airDb));deesser.coefficients=juce::dsp::IIR::Coefficients<float>::makePeakFilter(sr,6500,1.2f,juce::Decibels::decibelsToGain(-deEssDb));comp.setThreshold(threshold);comp.setRatio(ratio);comp.setAttack(8);comp.setRelease(90);comp.setKneeWidth(5);makeup.setGainDecibels(makeupDb);}
void AngelVocalAIProcessor::releaseResources(){}
void AngelVocalAIProcessor::startAnalysis(){analysing=true;analyzed=false;samples=0;target=(juce::int64)(sr*15);sumSq=peak=low=high=0;count=0;prev=0;}
void AngelVocalAIProcessor::processBlock(juce::AudioBuffer<float>& b,juce::MidiBuffer&){juce::ScopedNoDenormals nd;if(analysing){for(int i=0;i<b.getNumSamples();++i){float x=0;for(int c=0;c<b.getNumChannels();++c)x+=b.getSample(c,i);x/=std::max(1,b.getNumChannels());float ax=std::abs(x);peak=std::max(peak,ax);sumSq+=x*x;float lp=.985f*prev+.015f*x;prev=lp;low+=std::abs(lp);high+=std::abs(x-lp);++count;}samples+=b.getNumSamples();if(samples>=target){float rms=std::sqrt(sumSq/std::max<juce::int64>(1,count));float crest=peak/std::max(rms,.00001f),hr=high/std::max(.00001f,low+high);hpHz=juce::jlimit(55.f,120.f,65.f+hr*50);presDb=juce::jlimit(.5f,4.f,1.f+hr*5);airDb=juce::jlimit(0.f,3.f,.8f+hr*4);threshold=juce::jlimit(-30.f,-10.f,juce::Decibels::gainToDecibels(std::max(rms,.00001f))+(crest>5?2:-3));ratio=juce::jlimit(2.f,5.f,2.5f+(crest>4.5f?1.2f:0));makeupDb=juce::jlimit(0.f,5.f,-threshold*.07f);deEssDb=juce::jlimit(.2f,5.f,hr*8);outDb=juce::jlimit(-3.f,3.f,-juce::Decibels::gainToDecibels(std::max(rms,.00001f))*.08f);applySettings();analysing=false;analyzed=true;}}
juce::dsp::AudioBlock<float> block(b);juce::dsp::ProcessContextReplacing<float> ctx(block);hp.process(ctx);comp.process(ctx);makeup.process(ctx);presence.process(ctx);air.process(ctx);deesser.process(ctx);b.applyGain(juce::Decibels::decibelsToGain(outDb));}
juce::AudioProcessorEditor* AngelVocalAIProcessor::createEditor(){return new AngelVocalAIEditor(*this);}
void AngelVocalAIProcessor::getStateInformation(juce::MemoryBlock& d){juce::MemoryOutputStream m(d,true);for(float v:{hpHz,presDb,airDb,threshold,ratio,makeupDb,deEssDb,outDb})m.writeFloat(v);}
void AngelVocalAIProcessor::setStateInformation(const void* d,int n){if(n<32)return;juce::MemoryInputStream m(d,(size_t)n,false);hpHz=m.readFloat();presDb=m.readFloat();airDb=m.readFloat();threshold=m.readFloat();ratio=m.readFloat();makeupDb=m.readFloat();deEssDb=m.readFloat();outDb=m.readFloat();applySettings();analyzed=true;}
